### ISSUE TITLE
Nombreuses erreurs

### ISSUE THREAD

**Issue by Vierxa** [mguyard/Diagral-eOne-API-PHP#14]
Bonjour ,

Beaucoup d'erreurs sur l'utilisation de l'api depuis quelques jours.

Suis-je le seul ?
Cordialement,

**Comment by mguyard** [comment]
Bonjour,

Il y a en effet de très gros soucis avec les serveurs Diagral au global. Le problème est même visible au travers de l'Application mobile e-ONE.

J'ai initié un contact avec Diagral et Hager pour trouver une solution et établir une potentielle collaboration.
