### ISSUE TITLE
Ajout scenarios

### ISSUE THREAD

**Issue by Adsum02** [mguyard/Diagral-eOne-API-PHP#7]
Hello ! 
Tout d'abord un grand merci pour ce super travail que tu as fait :)

Je viens faire une demande de "enhancement" pour avoir la possibilité de récupérer les scenarios et de pouvoir les activer.

Ci-joint les captures d'écran correspondantes de l'application.
![menu](https://user-images.githubusercontent.com/48648557/54491601-0701f400-48c0-11e9-99d4-3882fbec0dfa.PNG)
![scenarios](https://user-images.githubusercontent.com/48648557/54491602-0701f400-48c0-11e9-8044-3143ce129ec1.PNG)

À disposition si besoin d'infos ou s'il faut tester :)

Bon courage et merci !

**Comment by mguyard** [comment]
Bonjour,

Je suis très pris en ce moment et je n’utilise pas cette feature à titre perso.
Je le met dans la todolist mais ne soit pas trop pressé

**Comment by Adsum02** [comment]
C'est noté, merci :)

**Comment by mguyard** [comment]
Je viens d'ajouter les scenarios.
- Les scenarios sont recuperable au travers de la fonction getScenarios() qui peut prendre en paramètre une regex (ou simplement le nom) pour filter (sur le nom du scenario).

`$MyAlarm->getScenarios(".*te.*")`

- Les scenarios sont executable au travers de la fonction launchScenario() qui prend en paramètre l'ID du scénario

`$MyAlarm->launchScenario(3);`

**Comment by Adsum02** [comment]
Merci !

Je teste ça dans la semaine et je reviens vers toi !

**Comment by mguyard** [comment]
Parfait. Je le passerais dans la branche stable dans la semaine
