### ISSUE TITLE
Erreur (à la déconnexion?)

### ISSUE THREAD

**Issue by Ganfoud** [mguyard/Diagral-eOne-API-PHP#8]
erreur suite à connexion/demande de l'état de l'alarme/déconnexion:
```
off[CRIT] - Logout Failed
Data Content :

Array
(
    [status] => KO
)
```
j'ai essayé de redémarrer la box diagral mais ça en change rien

**Comment by mguyard** [comment]
Je viens de pousser une correction dans le repo Develop. Tu peux tester ?

**Comment by Ganfoud** [comment]
Testé, validé !

**Comment by Vierxa** [comment]
Idem chez moi, cela fonctionne.

Grand Merci.

De : Ganfoud <notifications@github.com>
Répondre à : mguyard/Diagral-eOne-API-PHP <reply@reply.github.com>
Date : mardi 30 avril 2019 à 21:18
À : mguyard/Diagral-eOne-API-PHP <Diagral-eOne-API-PHP@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [mguyard/Diagral-eOne-API-PHP] Erreur (à la déconnexion?) (#8)


Testé, validé !

**Comment by mguyard** [comment]
Parfait merci.
Je clos donc cette issue.
